services:
  mysql:
    image: mysql:8.4
    container_name: retail_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_project_excel
      MYSQL_USER: retail_user
      MYSQL_PASSWORD: retail_pass
    ports:
      - "3310:3306"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    container_name: retail_adminer
    ports:
      - "8080:8080"

  metabase:
    image: metabase/metabase:latest
    container_name: retail_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
